version: 2.1 # Use version 2.1 to enable orb usage.

jobs: 
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/node-sdk-airtime/src
    # working_directory: ~/repo
    steps:
      - checkout
      - run: npm install --prefix node-sdk-airtime/src
      - run: npm install --prefix node-sdk-airtime/src --save-dev nyc
      - run: npm test --prefix node-sdk-airtime/src
