version: 2.1 # Use version 2.1 to enable orb usage.

jobs: 
  build:
    docker:
      - image: circleci/node:14.15.4
    working_directory: ~/node-sdk-core/src
    # working_directory: ~/repo
    steps:
      - checkout
      - run: npm install --prefix node-sdk-core/src
      - run: npm install --prefix node-sdk-core/src --save-dev nyc
      - run: npm test --prefix node-sdk-core/src
